### ISSUE TITLE
ability to prompt user for a directory to download all tabbed images ONCE - not for each image 

### ISSUE THREAD

**Issue by blurymind** [iqnivek/save_tabbed_images#37]
You can download only to c:/../downloads folder- it would be nice if there was the option to set the download directory once upon clicking the 'download images' button instead - with a normal save dialog prompt

**Comment by iqnivek** [comment]
I agree - I wanted to implement it that way to begin with, but the chrome extension API doesn't seem to enable that kind of functionality, as far as I know. Additionally, the chrome extension API doesn't support setting a download's destination programmatically to anything other than the default Downloads folder (or a subfolder of it). I would love it if it were possible to set any folder as well, but it's just not something that's possible based on what I've seen from the API. If anyone knows knows otherwise, please let me know!

**Comment by iqnivek** [comment]
Closing because this duplicates #22.
